### ISSUE TITLE
Connection exception

### ISSUE THREAD

**Issue by garak** [facile-it/doctrine-mysql-come-back#30]
Just tried to setup this in a project with Symfony 4.2 and got an ` InvalidArgumentException`:

> Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Connection needs a driver that implements ServerGoneAwayExceptionsAwareInterface  

here is my conf:

```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                url: '%env(resolve:DATABASE_URL)%'
                wrapper_class: 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Connection'
                driver_class: 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Driver\PDOMySql\Driver'
``

**Comment by taueres** [comment]
Hi, thanks for opening this issue!

According to DBAL documentation:
> The parameter `driverClass` specifies a custom driver implementation if no `driver` is specified. This allows the use of custom drivers that are not part of the Doctrine DBAL itself.

So the parameter `driver` has higher priority and will overwrite whatever is configured as `driverClass`.
Your configuration is declaring both parameters, please remove `driver` and the issue should be fixed.

**Comment by peelandsee** [comment]
@Jean85 are you sure?

what @taueres said seems pretty clear,
and the error comes from this lib because the wrapper class refuse a standard `pdo_mysql` driver implementation, missing that Interface.

@garak may you confirm your error was to declare `driver: 'pdo_mysql'`?

thanks,

**Comment by Jean85** [comment]
Oh sorry you're right, I misread @ŧaueres comment.

**Comment by silviokennecke** [comment]
@garak I had the same problem. According to the symfony documentation (https://symfony.com/doc/current/reference/configuration/doctrine.html) the configuration parameter `url` overrides the some of the configuration. This seems to happen with `driver_class`, too.
Try the following config:
``` yaml
# doctrine.yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                dbname: '%env(resolve:DATABASE_NAME)%'
                host: '%env(resolve:DATABASE_HOST)%'
                port: '%env(resolve:DATABASE_PORT)%'
                user: '%env(resolve:DATABASE_USER)%'
                password: '%env(resolve:DATABASE_PASSWORD)%'
                wrapper_class: 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Connection'
                driver_class: 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Driver\PDOMySql\Driver'
```
```
# .env
###> doctrine/doctrine-bundle ###
#DATABASE_URL=mysql://root:password@127.0.0.1:3306/dbname
DATABASE_NAME=dbname
DATABASE_HOST=127.0.0.1
DATABASE_PORT=3306
DATABASE_USER=root
DATABASE_PASSWORD=password
###< doctrine/doctrine-bundle ###
```
