### ISSUE TITLE
Timeouts despite the configuration is set according to the recommendation

### ISSUE THREAD

**Issue by c-schinzer** [facile-it/doctrine-mysql-come-back#62]
Hi,

strangely enough I still see timeouts when configuring as per [recommendation](https://github.com/facile-it/doctrine-mysql-come-back/blob/1.10.1/README.md#configuration). When analyzing the related Server Error I do not see any trace of `Facile` in it, while I think I should, the stack trace only refers to the `AbstractMySQLDriver`, `Doctrine/DBAL/Driver/PDOMySql/Driver`, `Doctrine/DBAL/Connection`.

How can I check that the configured Driver and Connection class are really loaded?
When running the `bin/console debug:container` command, I can see this
```
...
  doctrine.dbal.connection                                                                         Doctrine\DBAL\Connection                                                                        
  doctrine.dbal.connection.configuration                                                           Doctrine\DBAL\Configuration                                                                     
  doctrine.dbal.connection.event_manager                                                           Symfony\Bridge\Doctrine\ContainerAwareEventManager                                              
  doctrine.dbal.connection_factory                                                                 Doctrine\Bundle\DoctrineBundle\ConnectionFactory                                                
  doctrine.dbal.default_connection                                                                 Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Connection                                           
  doctrine.dbal.default_connection.configuration                                                   Doctrine\DBAL\Configuration                                                                     
  doctrine.dbal.default_connection.event_manager                                                   Symfony\Bridge\Doctrine\ContainerAwareEventManager                                              ...
```
Should it look like that?
Thanks for having a look.

Warm regards

Carsten

**Comment by c-schinzer** [comment]
Just for completeness, the config file:
```
doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver_class: 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Driver\PDOMySql\Driver'
                server_version: 'mariadb-10.1.40'
                wrapper_class: 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Connection'
                options:
                    x_reconnect_attempts: 5
```
